FROM nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf1.15-py3
RUN apt update &&  apt upgrade -y
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install -y python3.9-distutils

#RUN pip install --upgrade pip && pip install --upgrade distlib

RUN apt-get install -y protobuf-compiler libprotoc-dev

RUN apt install -y python3.9
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
RUN apt install -y python-pip
RUN pip install --upgrade pip && pip install --upgrade distlib
RUN pip install setuptools
RUN pip install torch
RUN pip install cmake
RUN pip install tensorflow --ignore-installed



RUN pip install jetson-stats
RUN apt install systemd -y
#RUN systemctl restart jetson_stats.service
